server_listen: :8080
# server_tls_key: cmd/go-graphkb/keys/server.key
# server_tls_cert: cmd/go-graphkb/keys/server.crt

mariadb_username: graphkb
mariadb_password: password
mariadb_host: db
mariadb_database: graphkb

# The level of concurrency allowed by the graph update API.
concurrency: 32

# Timeout for query handler
query_timeout: 60